### ISSUE TITLE
Half localization in french

### ISSUE THREAD

**Issue by Rajivhost** [johnkors/IdentityServer3.Contrib.Localization#31]
Hi,
Apparently, french localization not completely done?
![image](https://cloud.githubusercontent.com/assets/3539984/7591857/105d9190-f8c8-11e4-80c8-c62418961ea0.png)

**Comment by johnkors** [comment]
Yeah, there might be strings in the default views of identityserver that are not localized. For that, you would need (at least today) to implement your own views.

These are the keys of what _is_ translated:
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Resources/T4resx.cs

Example of text that is not covered by the localization extension of idsrv (for example using this repo/nuget).
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Services/DefaultViewService/PageAssets/consent.html#L25

@brockallen might have some opinions if complete localization is on the roadmap.

**Comment by Rajivhost** [comment]
Yes, indeed some parts of page not take care on localization extension. So, apparently the only option I have is to write my own views?

**Comment by johnkors** [comment]
Yes, but that's pretty easy. As easy as dropping a few html files in a folder if you just need to modify to hardcoded texts within the defaults.

**Comment by Rajivhost** [comment]
Ok, thanks for the support.
