### ISSUE TITLE
Views localization support for IdentityServer3

### ISSUE THREAD

**Issue by julianpaulozzi** [johnkors/IdentityServer3.Contrib.Localization#35]
I borrowed the prefix of this project because I want this house organized to take part of this project [IdentityServer3.Contrib.ViewLocalization](https://github.com/julianpaulozzi/IdentityServer3.Contrib.ViewLocalization).

Basically it's a angular way to translate the view based on the language requested by the browser and allowing user to change the language on demand.

After I talk more about it, but in the meantime I think already ready for viewing and testing.

**Comment by OsmanMElsayed** [comment]
Hi, another one already took a bit different approach, but you might be interested though. Check https://github.com/marmind/IdentityServer3.Contrib.Localization.UI

**Comment by julianpaulozzi** [comment]
Yes, [IdentityServer3.Contrib.ViewLocalization](https://github.com/julianpaulozzi/IdentityServer3.Contrib.ViewLocalization) ended up serving as angular-translate small lab.
With my [VS extension](https://visualstudiogallery.msdn.microsoft.com/24411980-e5da-406b-a87e-57666f114658) ended up being easier and safer to translate entire pages.
