### ISSUE TITLE
upgrade to work with idsrv3 v 2.0

### ISSUE THREAD

**Issue by totpero** [johnkors/IdentityServer3.Contrib.Localization#37]
Hello,
You need to make this to work with next idSrv3 v2.0, now is rc1 version but in first stable version will be major changes. One very important change is the namespaces, they remove the Thinktecture from namespace and from assembly name and other.
Here is the new nuget package: https://www.nuget.org/packages/IdentityServer3

**Comment by johnkors** [comment]
Solved in #41
