### ISSUE TITLE
Is there a new version for IDS3 2.0?

### ISSUE THREAD

**Issue by iltera** [johnkors/IdentityServer3.Contrib.Localization#38]
Now that it's out, are there any plans for it? As a matter of fact, I am waiting for this to make my ids upgrade to the new version.

**Comment by vidarkongsli** [comment]
+1

**Comment by johnkors** [comment]
Yeah, I've not been working with idsrv related projects lately, so sorry for the late feedback. Just merged #41 , so hopefully that solves it @iltera .

Pushed to nuget.org as:
http://www.nuget.org/packages/IdentityServer3.Localization/0.2.124
