### ISSUE TITLE
Detect current language

### ISSUE THREAD

**Issue by runes83** [johnkors/IdentityServer3.Contrib.Localization#54]
Does this detect the current language of the user and switch?
Or just enables to set a default language at startup?

**Comment by johnkors** [comment]
Enables a language set at startup.

**Comment by runes83** [comment]
Is there plans on making this switch based on the current language of the user?

**Comment by johnkors** [comment]
No, sorry. But should be doable by using the `OwinEnvironmentService`.

**Comment by johnkors** [comment]
Could this be of help?

https://github.com/johnkors/IdentityServer3.Contrib.Localization/pull/56

**Comment by runes83** [comment]
Yes this looks like a solution for us, I'll try it and report back :-)

**Comment by johnkors** [comment]
Sample added @ https://github.com/IdentityServer/IdentityServer3.Samples/pull/305

**Comment by johnkors** [comment]
Any luck?
